/**
 * PRUEBA DE LA MIGRACION de la invariante unica.
 *
 * La migracion
 * migrations/20260926_unique_admin_session_per_user_server.sql
 * ya esta aplicada en serverhub_test, de modo que la
 * restriccion UNIQUE (user_id, server_id) es permanente y no
 * se puede comprobar sobre admin_sessions: tras aplicarla es
 * imposible crear los duplicados que la limpieza debe
 * eliminar.
 *
 * Por eso la estrategia se verifica en un ESQUEMA TEMPORAL
 * AISLADO dentro de la misma base de pruebas. La tabla del
 * esquema replica las columnas relevantes de admin_sessions,
 * incluida la ausencia de UNIQUE (user_id, server_id), y se
 * aplica el MISMO archivo de migracion sobre ella, sin
 * reescribir el cuerpo. El esquema se elimina al terminar.
 *
 * Es PostgreSQL real: no hay mocks, ni simulacion, ni
 * sustitucion del motor. Y no se toca serverhub.
 *
 * Ademas se comprueba, sobre la tabla real ya migrada, que la
 * restriccion existe con la definicion esperada y que un
 * INSERT duplicado produce 23505 con el nombre correcto.
 */

const {
    test,
    before,
    after
} = require("node:test");

const assert =
    require("node:assert/strict");

const fs =
    require("fs");

const path =
    require("path");

const crypto =
    require("crypto");

/**
 * database.helper.js debe ser el primer require: inyecta la
 * configuracion de la base de pruebas antes de que se
 * construya el Pool de ../../src/config/db.
 */
const {
    verifyTestConnection,
    getTestPool
} = require("../helpers/database.helper");

const MIGRATION_PATH =
    path.resolve(
        __dirname,
        "..",
        "..",
        "migrations",
        "20260926_unique_admin_session_per_user_server.sql"
    );

const MIGRATION_SQL =
    fs.readFileSync(
        MIGRATION_PATH,
        "utf8"
    );

const ESQUEMA =
    "f96_migracion";

const NOMBRE_RESTRICCION =
    "admin_sessions_user_server_key";

const TABLA =
    '"' + ESQUEMA + '"."admin_sessions"';

/**
 * Redirige la migracion al esquema temporal. Solo cualifica
 * el nombre de la tabla, porque el nombre de la restriccion
 * es un sufijo que no incluye el de la tabla. El cuerpo del
 * archivo se conserva intacto, incluida la sentencia
 * DELETE, el ORDER BY y la ausencia de IF NOT EXISTS.
 */
function migracionParaEsquema() {

    return MIGRATION_SQL.replace(
        /(FROM|INTO|TABLE)\s+admin_sessions/g,
        (match, palabra) =>
            palabra + " " + TABLA
    );

}

before(async () => {

    const info =
        await verifyTestConnection();

    assert.equal(
        info.database,
        "serverhub_test"
    );

    const existe =
        fs.existsSync(
            MIGRATION_PATH
        );

    assert.ok(
        existe,
        "el archivo de migracion debe existir"
    );

});

after(async () => {

    const pool =
        getTestPool();

    await pool.query(
        "DROP SCHEMA IF EXISTS " +
        ESQUEMA + " CASCADE"
    );

});

async function crearTablaTemporal() {

    const pool =
        getTestPool();

    await pool.query(
        "DROP SCHEMA IF EXISTS " +
        ESQUEMA + " CASCADE"
    );

    await pool.query(
        "CREATE SCHEMA " + ESQUEMA
    );

    /**
     * Mismas columnas que admin_sessions, y solo las
     * restricciones que tenia antes de la migracion: PRIMARY
     * KEY e UNIQUE (token). A proposito NO lleva
     * UNIQUE (user_id, server_id).
     */
    await pool.query(
        `CREATE TABLE ` + TABLA + ` (
            id integer
                GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
            server_id integer NOT NULL,
            user_id integer NOT NULL,
            token text NOT NULL UNIQUE,
            expires_at timestamp NOT NULL,
            created_at timestamp
                DEFAULT CURRENT_TIMESTAMP
        )`
    );

}

/**
 * Inserta una sesion con created_at controlado. La marca
 * temporal se construye en SQL a partir de epoch para
 * evitar la doble conversion de zona horaria que node-postgres
 * introduce al serializar un Date.
 */
async function insertarSesion(
    userId,
    serverId,
    minutoRelativo
) {

    const pool =
        getTestPool();

    const epoch =
        Date.now() +
        minutoRelativo * 60 * 1000;

    const result =
        await pool.query(
            `INSERT INTO ` + TABLA + `
                (
                    user_id,
                    server_id,
                    token,
                    expires_at,
                    created_at
                )
             VALUES (
                $1,
                $2,
                $3,
                to_timestamp($4::double precision / 1000),
                to_timestamp($5::double precision / 1000)
                     AT TIME ZONE 'UTC'
            )
            RETURNING id`,
            [
                userId,
                serverId,
                crypto
                    .randomBytes(32)
                    .toString("hex"),
                Date.now() + 900000,
                epoch
            ]
        );

    return result.rows[0].id;

}

async function idsDeCombinacion(
    userId,
    serverId
) {

    const pool =
        getTestPool();

    const result =
        await pool.query(
            `SELECT id
             FROM ` + TABLA + `
             WHERE user_id = $1
             AND server_id = $2
             ORDER BY id`,
            [userId, serverId]
        );

    return result.rows.map(
        row => row.id
    );

}

test(
    "el archivo de migración usa una transacción y la restricción esperada",
    () => {

        assert.match(
            MIGRATION_SQL,
            /BEGIN\s*;/
        );

        assert.match(
            MIGRATION_SQL,
            /COMMIT\s*;/
        );

        assert.match(
            MIGRATION_SQL,
            /ROW_NUMBER\(\)\s+OVER/
        );

        assert.match(
            MIGRATION_SQL,
            /PARTITION\s+BY\s+user_id\s*,\s*server_id/
        );

        assert.match(
            MIGRATION_SQL,
            /ORDER\s+BY\s+created_at\s+DESC\s*,\s*id\s+DESC/
        );

        assert.match(
            MIGRATION_SQL,
            /WHERE\s+numeradas\.fila\s*>\s*1/
        );

        assert.match(
            MIGRATION_SQL,
            /ADD\s+CONSTRAINT\s+admin_sessions_user_server_key\s+UNIQUE/
        );

        /**
         * Nada de lo prohibido.
         */
        assert.doesNotMatch(
            MIGRATION_SQL,
            /TRUNCATE/i
        );

        assert.doesNotMatch(
            MIGRATION_SQL,
            /CASCADE/i
        );

        assert.doesNotMatch(
            MIGRATION_SQL,
            /DROP\s+TABLE/i
        );

        assert.doesNotMatch(
            MIGRATION_SQL,
            /RESTART\s+SEQUENCE/i
        );

        assert.doesNotMatch(
            MIGRATION_SQL,
            /\\connect/i
        );

        assert.doesNotMatch(
            MIGRATION_SQL,
            /PASSWORD/i
        );

        assert.doesNotMatch(
            MIGRATION_SQL,
            /IF\s+NOT\s+EXISTS/i,
            "no debe ser silenciosamente idempotente"
        );

    }
);

test(
    "la limpieza conserva la fila más reciente y borra el resto",
    async () => {

        await crearTablaTemporal();

        const antigua =
            await insertarSesion(1, 1, -180);
        const intermedia =
            await insertarSesion(1, 1, -90);
        const reciente =
            await insertarSesion(1, 1, -5);

        const antes =
            await idsDeCombinacion(1, 1);

        assert.equal(
            antes.length,
            3
        );

        const pool =
            getTestPool();

        await pool.query(
            migracionParaEsquema()
        );

        const despues =
            await idsDeCombinacion(1, 1);

        assert.equal(
            despues.length,
            1,
            "debe quedar exactamente una fila"
        );

        assert.equal(
            despues[0],
            reciente,
            "debe conservar la mas reciente"
        );

        assert.ok(
            !despues.includes(antigua)
        );

        assert.ok(
            !despues.includes(intermedia)
        );

    }
);

test(
    "con empate en created_at se conserva el id mayor",
    async () => {

        await crearTablaTemporal();

        const masReciente =
            await insertarSesion(1, 1, -5);

        const empateBajo =
            await insertarSesion(1, 1, -1);
        const empateAlto =
            await insertarSesion(1, 1, -1);

        assert.ok(
            empateAlto > empateBajo
        );

        const pool =
            getTestPool();

        await pool.query(
            migracionParaEsquema()
        );

        const supervivientes =
            await idsDeCombinacion(1, 1);

        assert.equal(
            supervivientes.length,
            1
        );

        assert.equal(
            supervivientes[0],
            empateAlto,
            "en el empate gana el id mayor"
        );

        assert.equal(
            supervivientes[0] ===
                masReciente,
            false,
            "y no la de created_at mas " +
            "antigua"
        );

    }
);

test(
    "las combinaciones sin duplicados no se alteran",
    async () => {

        await crearTablaTemporal();

        await insertarSesion(1, 1, -90);
        await insertarSesion(2, 2, -90);
        await insertarSesion(2, 3, -90);

        const pool =
            getTestPool();

        await pool.query(
            migracionParaEsquema()
        );

        const primera =
            await idsDeCombinacion(1, 1);
        const segunda =
            await idsDeCombinacion(2, 2);
        const tercera =
            await idsDeCombinacion(2, 3);

        assert.equal(primera.length, 1);
        assert.equal(segunda.length, 1);
        assert.equal(tercera.length, 1);

        const total =
            await pool.query(
                "SELECT count(*)::int AS total FROM " +
                TABLA
            );

        assert.equal(
            total.rows[0].total,
            3
        );

    }
);

test(
    "la restricción instalada rechaza el duplicado con 23505",
    async () => {

        await crearTablaTemporal();

        const original =
            await insertarSesion(1, 1, -90);

        const pool =
            getTestPool();

        await pool.query(
            migracionParaEsquema()
        );

        const definicion =
            await pool.query(
                `SELECT pg_get_constraintdef(oid) AS def
                 FROM pg_constraint
                 WHERE conrelid = $1::regclass
                   AND conname = $2`,
                [
                    ESQUEMA + ".admin_sessions",
                    NOMBRE_RESTRICCION
                ]
            );

        assert.equal(
            definicion.rows.length,
            1
        );

        assert.equal(
            definicion.rows[0].def,
            "UNIQUE (user_id, server_id)"
        );

        let error = null;

        try {

            await insertarSesion(1, 1, -1);

        } catch (e) {

            error = e;

        }

        assert.ok(
            error,
            "el duplicado debe rechazarse"
        );

        assert.equal(
            error.code,
            "23505"
        );

        assert.equal(
            error.constraint,
            NOMBRE_RESTRICCION
        );

        /**
         * Y la original sigue intacta.
         */
        const supervivientes =
            await idsDeCombinacion(1, 1);

        assert.equal(
            supervivientes.length,
            1
        );

        assert.equal(
            supervivientes[0],
            original
        );

    }
);

test(
    "una segunda ejecución falla de forma clara",
    async () => {

        await crearTablaTemporal();

        const pool =
            getTestPool();

        await pool.query(
            migracionParaEsquema()
        );

        let error = null;

        try {

            await pool.query(
                migracionParaEsquema()
            );

        } catch (e) {

            error = e;

        }

        assert.ok(
            error,
            "la segunda ejecución debe fallar"
        );

        /**
         * 42P07 es duplicate_object: la restriccion ya
         * existe. Es exactamente el fallo que se quiere
         * detectar en lugar de ocultarlo.
         */
        assert.equal(
            error.code,
            "42P07"
        );

        assert.match(
            error.message,
            /admin_sessions_user_server_key/
        );

        await pool.query("ROLLBACK");

    }
);

test(
    "la tabla real ya migrada tiene la restricción y rechaza duplicados",
    async () => {

        const pool =
            getTestPool();

        const definicion =
            await pool.query(
                `SELECT pg_get_constraintdef(oid) AS def
                 FROM pg_constraint
                 WHERE conrelid =
                        'public.admin_sessions'::regclass
                   AND conname = $1`,
                [NOMBRE_RESTRICCION]
            );

        assert.equal(
            definicion.rows.length,
            1,
            "la restricción debe estar instalada " +
            "en admin_sessions"
        );

        assert.equal(
            definicion.rows[0].def,
            "UNIQUE (user_id, server_id)"
        );

        /**
         * Comprobacion real del rechazo, sin dejar rastro:
         * se intenta un duplicado dentro de una transaccion
         * que se deshace.
         */
        const { createTestUser, createTestServer, cleanupTestData } =
            require("../helpers/database.helper");

        const user =
            await createTestUser();

        const server =
            await createTestServer({
                userId: user.id
            });

        const cliente =
            await pool.connect();

        let error = null;

        try {

            await cliente.query("BEGIN");

            for (
                const intento of [1, 2]
            ) {

                await cliente.query(
                    `INSERT INTO admin_sessions
                        (
                            user_id,
                            server_id,
                            token,
                            expires_at
                        )
                     VALUES ($1, $2, $3, $4)`,
                    [
                        user.id,
                        server.id,
                        crypto
                            .randomBytes(32)
                            .toString("hex"),
                        new Date(
                            Date.now() +
                            900000
                        )
                    ]
                );

            }

        } catch (e) {

            error = e;

        } finally {

            await cliente.query("ROLLBACK");
            cliente.release();

        }

        await cleanupTestData({
            userIds: [user.id],
            serverIds: [server.id]
        });

        assert.ok(
            error,
            "el segundo INSERT debe fallar"
        );

        assert.equal(
            error.code,
            "23505"
        );

        assert.equal(
            error.constraint,
            NOMBRE_RESTRICCION
        );

    }
);
